#!/bin/bash
set -euo pipefail

# ──────────────────────────────────────────────────────────────
# Major Tom — Cloudflare Named Tunnel Setup
#
# This script creates a persistent Cloudflare Tunnel so the
# relay server is accessible from your phone without ad-hoc
# tunnel commands.
#
# Prerequisites:
#   - cloudflared installed (brew install cloudflared)
#   - A domain managed by Cloudflare
#
# This script is idempotent — safe to re-run.
# ──────────────────────────────────────────────────────────────

TUNNEL_NAME="major-tom"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG_FILE="${SCRIPT_DIR}/config.yml"

# ── Colors ───────────────────────────────────────────────────

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

info()  { echo -e "${CYAN}ℹ${NC}  $1"; }
ok()    { echo -e "${GREEN}✓${NC}  $1"; }
warn()  { echo -e "${YELLOW}⚠${NC}  $1"; }
fail()  { echo -e "${RED}✗${NC}  $1"; exit 1; }

# ── Step 1: Check cloudflared is installed ───────────────────

if ! command -v cloudflared &>/dev/null; then
  fail "cloudflared is not installed. Install it with:\n\n  brew install cloudflared\n"
fi
ok "cloudflared is installed ($(cloudflared --version 2>&1 | head -1))"

# ── Step 2: Check login / auth ──────────────────────────────

if ! cloudflared tunnel list &>/dev/null; then
  warn "Not logged in to Cloudflare. Running login..."
  echo ""
  cloudflared tunnel login
  echo ""
fi
ok "Authenticated with Cloudflare"

# ── Step 3: Create tunnel (or reuse existing) ───────────────

TUNNEL_ID=$(cloudflared tunnel list 2>/dev/null | awk -v name="${TUNNEL_NAME}" '$2 == name {print $1; exit}')
if [ -n "${TUNNEL_ID}" ]; then
  ok "Tunnel '${TUNNEL_NAME}' already exists (ID: ${TUNNEL_ID})"
else
  info "Creating tunnel '${TUNNEL_NAME}'..."
  cloudflared tunnel create "${TUNNEL_NAME}"
  TUNNEL_ID=$(cloudflared tunnel list 2>/dev/null | awk -v name="${TUNNEL_NAME}" '$2 == name {print $1; exit}')
  ok "Tunnel created (ID: ${TUNNEL_ID})"
fi

if [ -z "${TUNNEL_ID}" ]; then
  fail "Could not determine tunnel ID. Check 'cloudflared tunnel list' manually."
fi

# ── Step 4: Ask for hostname ─────────────────────────────────

echo ""
echo -e "${CYAN}Enter the hostname to route to Major Tom.${NC}"
echo "This should be a subdomain on a Cloudflare-managed domain."
echo "Example: majortom.yourdomain.com"
echo ""
read -rp "Hostname: " HOSTNAME

if [ -z "${HOSTNAME}" ]; then
  fail "Hostname cannot be empty."
fi

# ── Step 5: Create DNS route ────────────────────────────────

info "Creating DNS route: ${HOSTNAME} → tunnel '${TUNNEL_NAME}'..."
if ROUTE_OUTPUT="$(cloudflared tunnel route dns "${TUNNEL_NAME}" "${HOSTNAME}" 2>&1)"; then
  ok "DNS route created for ${HOSTNAME}"
else
  if echo "${ROUTE_OUTPUT}" | grep -qi "already exists"; then
    warn "DNS route already exists for ${HOSTNAME} (this is fine if re-running setup)"
  else
    fail "Failed to create DNS route for ${HOSTNAME}.\\ncloudflared output:\\n${ROUTE_OUTPUT}"
  fi
fi

# ── Step 6: Generate config.yml ──────────────────────────────

CREDS_FILE="${HOME}/.cloudflared/${TUNNEL_ID}.json"

cat > "${CONFIG_FILE}" <<YAML
# Major Tom — Cloudflare Tunnel Configuration
# Generated by setup.sh — do not commit this file

tunnel: ${TUNNEL_ID}
credentials-file: ${CREDS_FILE}

ingress:
  - hostname: ${HOSTNAME}
    service: http://localhost:9090
  - service: http_status:404
YAML

ok "Config written to ${CONFIG_FILE}"

# ── Done ─────────────────────────────────────────────────────

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${GREEN}Setup complete!${NC}"
echo ""
echo "  URL:   https://${HOSTNAME}"
echo "  WS:    wss://${HOSTNAME}"
echo ""
echo "  Start the tunnel:"
echo "    cd relay && npm run tunnel"
echo ""
echo "  Or start relay + tunnel together:"
echo "    cd relay && npm run dev:remote"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
