#!/usr/bin/env bash
# Major Tom — PreToolUse hook
#
# Installed by relay/scripts/install-hooks.ts to:
#   $HOME/.major-tom/claude-config/hooks/pretooluse.sh
#
# Routes tool-approval prompts through the relay according to the routing
# mode in $MAJOR_TOM_CONFIG_DIR/approval-mode.json.
#
# DO NOT edit this file by hand — the relay's install-hooks step will
# detect a hash mismatch on next startup and overwrite it from the bundled
# template at relay/scripts/hook-templates/pretooluse.sh.
set -euo pipefail

PAYLOAD=$(cat)
CONFIG_DIR="${MAJOR_TOM_CONFIG_DIR:-$HOME/.major-tom/claude-config}"
RELAY_PORT="${MAJOR_TOM_RELAY_PORT:-9091}"
TAB_ID="${MAJOR_TOM_TAB_ID:-unknown}"
RELAY_URL="http://127.0.0.1:${RELAY_PORT}/hooks/pre-tool-use"

# Read mode per-invocation. Fall back to env var, then 'local'.
if command -v jq >/dev/null 2>&1 && [ -f "$CONFIG_DIR/approval-mode.json" ]; then
  MODE=$(jq -r '.mode // "local"' < "$CONFIG_DIR/approval-mode.json" 2>/dev/null || echo "local")
else
  MODE="${MAJOR_TOM_APPROVAL:-local}"
fi

# Detect bypass mode in the payload — Claude Code #37420 escape hatch.
# Bypass mode means the user launched with --dangerously-skip-permissions.
# If we return 'ask' here, we permanently disable bypass for the rest of
# the session. So we just allow and let the relay log it.
if command -v jq >/dev/null 2>&1; then
  PERMISSION_MODE=$(printf '%s' "$PAYLOAD" | jq -r '.permission_mode // empty' 2>/dev/null || true)
else
  PERMISSION_MODE=""
fi
if [ "$PERMISSION_MODE" = "bypassPermissions" ]; then
  echo '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"allow"}}'
  exit 0
fi

case "$MODE" in
  local)
    # Fire and forget — never block the TUI
    curl -fsS --max-time 1 -X POST "$RELAY_URL" \
      -H "Content-Type: application/json" \
      -H "X-MT-Mode: local" \
      -H "X-MT-Tab: $TAB_ID" \
      -d "$PAYLOAD" >/dev/null 2>&1 &
    echo '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"ask"}}'
    ;;
  remote)
    # Block waiting for the phone. The relay returns the full envelope.
    DECISION_JSON=$(curl -fsS --max-time 600 -X POST "$RELAY_URL" \
      -H "Content-Type: application/json" \
      -H "X-MT-Mode: remote" \
      -H "X-MT-Tab: $TAB_ID" \
      -d "$PAYLOAD")
    echo "$DECISION_JSON"
    ;;
  hybrid)
    # Notify the phone, but also let the TUI prompt. tmux send-keys
    # races on the relay side if the phone wins.
    curl -fsS --max-time 1 -X POST "$RELAY_URL" \
      -H "Content-Type: application/json" \
      -H "X-MT-Mode: hybrid" \
      -H "X-MT-Tab: $TAB_ID" \
      -d "$PAYLOAD" >/dev/null 2>&1 &
    echo '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"ask"}}'
    ;;
  *)
    # Unknown mode — fall back to local behavior
    echo '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"ask"}}'
    ;;
esac
