#!/usr/bin/env bash
# Major Tom — SessionStart hook
#
# Installed by relay/src/installer/install-hooks.ts to:
#   $HOME/.major-tom/claude-config/hooks/session-start.sh
#
# Fires whenever `claude` boots inside an iOS terminal tab (via the
# CLAUDE_CONFIG_DIR env injected by shell.ts). Tells the relay that a
# new session is alive inside this tab so the Office Manager can show it.
#
# DO NOT edit this file by hand — the relay's install-hooks step will
# detect a hash mismatch on next startup and overwrite it from the bundled
# template at relay/scripts/hook-templates/session-start.sh.
set -euo pipefail

PAYLOAD=$(cat)
RELAY_PORT="${MAJOR_TOM_RELAY_PORT:-9091}"
TAB_ID="${MAJOR_TOM_TAB_ID:-unknown}"
RELAY_URL="http://127.0.0.1:${RELAY_PORT}/hooks/session-start"

# Fire and forget — never block claude's boot. If the relay is down or
# slow, claude should still start; the user can reconnect the Office later.
curl -fsS --max-time 1 -X POST "$RELAY_URL" \
  -H "Content-Type: application/json" \
  -H "X-MT-Tab: $TAB_ID" \
  -d "$PAYLOAD" >/dev/null 2>&1 &

# SessionStart hook expects an empty JSON object to signal "no override".
echo '{}'
