#!/usr/bin/env bash
# Major Tom — SessionEnd hook (/exit, /clear, /logout, etc.)
#
# Installed by relay/src/installer/install-hooks.ts to:
#   $HOME/.major-tom/claude-config/hooks/sessionend.sh
#
# Claude Code fires this when a session terminates. Unlike `Stop` (which
# runs when the agent finishes responding), SessionEnd covers the paths
# where the user ends the session themselves: `/exit`, `/clear`, `/logout`,
# closing the terminal, etc. Payload includes a `reason` field with
# matcher values like `prompt_input_exit`, `clear`, `resume`, `logout`,
# `bypass_permissions_disabled`, `other`.
#
# Without this hook, typing `/exit` leaves the Major Tom session "active"
# forever and any still-linked subagents stay as zombie sprites in the
# iOS Office (QA-FIXES.md #7b root cause).
#
# DO NOT edit this file by hand — the relay's install-hooks step will
# detect a hash mismatch on next startup and overwrite it from the
# bundled template at relay/scripts/hook-templates/sessionend.sh.
set -euo pipefail

PAYLOAD=$(cat)
RELAY_PORT="${MAJOR_TOM_RELAY_PORT:-9091}"
TAB_ID="${MAJOR_TOM_TAB_ID:-unknown}"
RELAY_URL="http://127.0.0.1:${RELAY_PORT}/hooks/session-end"

# Fire and forget — never block the shutdown path.
curl -fsS --max-time 1 -X POST "$RELAY_URL" \
  -H "Content-Type: application/json" \
  -H "X-MT-Tab: $TAB_ID" \
  -d "$PAYLOAD" >/dev/null 2>&1 &

# SessionEnd expects an empty JSON object to signal "no override".
echo '{}'
