#!/usr/bin/env bash
# Major Tom — Stop hook (Claude Code's session-end signal)
#
# Installed by relay/src/installer/install-hooks.ts to:
#   $HOME/.major-tom/claude-config/hooks/stop.sh
#
# Fires when the main claude agent stops (user types `exit`, ^D, or the
# process terminates). Tells the relay to mark the session closed and the
# tab idle. The tab itself survives — it is torn down only when the PTY
# disconnect grace expires (see pty-adapter.ts).
#
# DO NOT edit this file by hand — the relay's install-hooks step will
# detect a hash mismatch on next startup and overwrite it from the bundled
# template at relay/scripts/hook-templates/stop.sh.
set -euo pipefail

PAYLOAD=$(cat)
RELAY_PORT="${MAJOR_TOM_RELAY_PORT:-9091}"
TAB_ID="${MAJOR_TOM_TAB_ID:-unknown}"
RELAY_URL="http://127.0.0.1:${RELAY_PORT}/hooks/stop"

# Fire and forget — never block the shutdown path.
curl -fsS --max-time 1 -X POST "$RELAY_URL" \
  -H "Content-Type: application/json" \
  -H "X-MT-Tab: $TAB_ID" \
  -d "$PAYLOAD" >/dev/null 2>&1 &

# Stop hook expects an empty JSON object to signal "no override".
echo '{}'
