#!/usr/bin/env bash
# Major Tom — SubagentStart hook (Wave 2 placeholder)
#
# Installed by relay/src/installer/install-hooks.ts to:
#   $HOME/.major-tom/claude-config/hooks/subagent-start.sh
#
# Wave 2 just logs the event to the relay so we can confirm the hook fires.
# Wave 3 will use this to broadcast spawn-time agent metadata to the PWA.
#
# DO NOT edit this file by hand — the relay's install-hooks step will
# detect a hash mismatch on next startup and overwrite it from the bundled
# template at relay/scripts/hook-templates/subagent-start.sh.
set -euo pipefail

PAYLOAD=$(cat)
RELAY_PORT="${MAJOR_TOM_RELAY_PORT:-9091}"
TAB_ID="${MAJOR_TOM_TAB_ID:-unknown}"
RELAY_URL="http://127.0.0.1:${RELAY_PORT}/hooks/subagent-start"

# Fire and forget — never block subagent spawn.
curl -fsS --max-time 1 -X POST "$RELAY_URL" \
  -H "Content-Type: application/json" \
  -H "X-MT-Tab: $TAB_ID" \
  -d "$PAYLOAD" >/dev/null 2>&1 &

# SubagentStart hook does NOT use the PreToolUse envelope — empty object
# is the no-op shape per the Claude Code hook spec.
echo '{}'
