#!/usr/bin/env bash
# Major Tom — SubagentStop hook (Phase 13 Wave 3)
#
# Installed by relay/src/installer/install-hooks.ts to:
#   $HOME/.major-tom/claude-config/hooks/subagent-stop.sh
#
# Posts the SubagentStop hook payload to the relay's loopback hook
# server so the sprite layer can dismiss the sprite when a PTY-spawned
# subagent finishes. Fire-and-forget so we never block the parent
# session.
#
# DO NOT edit this file by hand — the relay's install-hooks step will
# detect a hash mismatch on next startup and overwrite it from the bundled
# template at relay/scripts/hook-templates/subagent-stop.sh.
set -euo pipefail

PAYLOAD=$(cat)
RELAY_PORT="${MAJOR_TOM_RELAY_PORT:-9091}"
TAB_ID="${MAJOR_TOM_TAB_ID:-unknown}"
RELAY_URL="http://127.0.0.1:${RELAY_PORT}/hooks/subagent-stop"

# Fire and forget — never block subagent shutdown.
curl -fsS --max-time 1 -X POST "$RELAY_URL" \
  -H "Content-Type: application/json" \
  -H "X-MT-Tab: $TAB_ID" \
  -d "$PAYLOAD" >/dev/null 2>&1 &

# SubagentStop hook does NOT use the PreToolUse envelope — empty object
# is the no-op shape per the Claude Code hook spec.
echo '{}'
